# Generated by Django 3.2.7 on 2023-02-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('bingo_location', models.IntegerField()),
                ('score', models.IntegerField()),
                ('bingo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.bingo')),
                ('special_tile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.specialtile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('is_mod_disapproved', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tile.tile')),
            ],
        ),
    ]
