# Generated by Django 4.2.7 on 2023-11-03 20:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('bingo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Tile Name', help_text='Text limit: 64 Characters, Recommended less than 16', max_length=64)),
                ('description', models.TextField(default='Description', help_text='Text limit: 512 Characters', max_length=512)),
                ('img', models.ImageField(blank=True, help_text='Image associated with Tile. Recommended size: 270x200px', null=True, upload_to='')),
                ('bingo_location', models.IntegerField()),
                ('score', models.IntegerField(default=1)),
                ('is_ready', models.BooleanField(default=False)),
                ('invocation_type', models.CharField(choices=[('SBM', 'Submission'), ('WOM', 'WiseOldMan')], default='SBM', max_length=3)),
                ('object_id', models.UUIDField()),
                ('bingo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.bingo')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='TeamTile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(default=True)),
                ('is_skipped', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(null=True)),
                ('is_mod_approved', models.BooleanField(default=False)),
                ('mod_approval_date', models.DateTimeField(null=True)),
                ('score', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tile.tile')),
            ],
        ),
    ]
