# Generated by Django 4.1.7 on 2023-08-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='description',
            field=models.CharField(default='Description', max_length=256),
        ),
        migrations.AlterField(
            model_name='tile',
            name='name',
            field=models.CharField(default='Tile Name', max_length=64),
        ),
    ]
