# Generated by Django 4.2.7 on 2023-11-04 15:34

import applications.defaults.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='img',
            field=models.ImageField(blank=True, help_text='Image associated with Tile. Recommended size: 270x200px', null=True, storage=applications.defaults.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
