# Generated by Django 4.1.7 on 2023-08-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0002_alter_tile_description_alter_tile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamtile',
            old_name='is_mod_disapproved',
            new_name='is_mod_approved',
        ),
    ]
