# Generated by Django 4.2.7 on 2023-11-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0002_tileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileimage',
            name='background',
            field=models.CharField(choices=[('_', 'Transparent')], default='_', max_length=64),
        ),
        migrations.AlterField(
            model_name='tileimage',
            name='style',
            field=models.CharField(choices=[('_', 'Wiki')], default='_', max_length=64),
        ),
    ]
