# Generated by Django 4.1.7 on 2023-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0003_rename_is_mod_disapproved_teamtile_is_mod_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtile',
            name='completion_date',
            field=models.DateTimeField(null=True),
        ),
    ]
