# Generated by Django 4.2.7 on 2023-11-18 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0003_alter_tileimage_background_alter_tileimage_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='pack_image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.tileimage'),
        ),
    ]
