# Generated by Django 4.1.7 on 2023-08-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0004_teamtile_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtile',
            name='mod_approval_date',
            field=models.DateTimeField(null=True),
        ),
    ]
