# Generated by Django 4.1.7 on 2023-08-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0005_teamtile_mod_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
