# Generated by Django 4.1.7 on 2023-08-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0006_tile_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tile',
            old_name='is_read',
            new_name='is_ready',
        ),
    ]
