# Generated by Django 4.1.7 on 2023-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0007_rename_is_read_tile_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtile',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
