# Generated by Django 4.1.7 on 2023-08-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0008_teamtile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamtile',
            name='img',
        ),
        migrations.AddField(
            model_name='tile',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
