# Generated by Django 4.1.7 on 2023-08-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0009_remove_teamtile_img_tile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
