# Generated by Django 4.1.7 on 2023-08-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0010_alter_tile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
