# Generated by Django 4.1.7 on 2023-09-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0012_alter_tile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='description',
            field=models.TextField(default='Description', max_length=512),
        ),
    ]
