# Generated by Django 4.1.7 on 2023-09-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tile', '0013_alter_tile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='special_tile',
        ),
        migrations.AddField(
            model_name='tile',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tile',
            name='object_id',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
    ]
