# Generated by Django 4.1.7 on 2023-09-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tile', '0014_remove_tile_special_tile_tile_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='content_type',
            field=models.ForeignKey(to='contenttypes.contenttype'),
        ),
    ]
