# Generated by Django 4.1.7 on 2023-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0015_alter_tile_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='invocation_type',
            field=models.CharField(choices=[('SBM', 'Submission'), ('WOS', 'WiseOldMan')], default='SBM', max_length=3),
        ),
    ]
