# Generated by Django 4.1.7 on 2023-09-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0016_tile_invocation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='invocation_type',
            field=models.CharField(choices=[('SBM', 'Submission'), ('WOM', 'WiseOldMan')], default='SBM', max_length=3),
        ),
    ]
