# Generated by Django 4.1.7 on 2023-09-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0017_alter_tile_invocation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
