# Generated by Django 4.1.7 on 2023-10-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0018_teamtile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='img',
            field=models.ImageField(blank=True, help_text='Image associated with Tile. Recommended size: 270x200px', null=True, upload_to=''),
        ),
    ]
