# Generated by Django 4.1.7 on 2023-10-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0019_alter_tile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='description',
            field=models.TextField(default='Description', help_text='Text limit: 512 Characters', max_length=512),
        ),
        migrations.AlterField(
            model_name='tile',
            name='name',
            field=models.CharField(default='Tile Name', help_text='Text limit: 64 Characters, Recommended less than 16', max_length=64),
        ),
    ]
