# Generated by Django 4.2.7 on 2023-11-03 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tile', '0001_initial'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='team_tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tile.teamtile'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='team_tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tile.teamtile'),
        ),
    ]
