# Generated by Django 4.1.7 on 2023-08-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_alter_submission_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
