# Generated by Django 4.1.7 on 2023-08-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_player_teams'),
        ('tile', '0005_teamtile_mod_approval_date'),
        ('submission', '0005_alter_submission_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
                ('team_tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tile.teamtile')),
            ],
        ),
    ]
