# Generated by Django 4.1.7 on 2023-08-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_remove_achievement_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='status',
        ),
        migrations.AddField(
            model_name='achievement',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
