# Generated by Django 4.1.7 on 2023-09-03 19:17

import applications.defaults.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_remove_achievement_status_achievement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='img',
            field=models.ImageField(storage=applications.defaults.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
