# Generated by Django 4.1.7 on 2023-08-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_alter_bingo_max_score'),
        ('player', '0002_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bingo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_bingo', to='bingo.bingo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_player', to='player.player')),
            ],
        ),
    ]
