# Generated by Django 4.1.7 on 2023-08-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_player', to='player.player'),
        ),
    ]
