# Generated by Django 4.1.7 on 2023-08-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_alter_bingo_max_score'),
        ('player', '0004_alter_moderator_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bingos',
            field=models.ManyToManyField(to='bingo.bingo'),
        ),
    ]
