# Generated by Django 4.1.7 on 2023-08-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_bingo_score_alter_team_ranking'),
        ('player', '0005_player_bingos'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(to='team.team'),
        ),
    ]
