# Generated by Django 4.1.7 on 2023-09-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_ranking'),
        ('player', '0007_playerbingodetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbingodetail',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
