# Generated by Django 4.2.7 on 2023-11-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_playerbingodetail_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bingos',
        ),
        migrations.RemoveField(
            model_name='player',
            name='teams',
        ),
    ]
