# Generated by Django 4.1.7 on 2023-09-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0015_alter_tile_content_type'),
        ('invocation', '0002_submissioninvo_wosinvo_delete_invocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioninvo',
            name='tile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tile.tile'),
        ),
        migrations.AddField(
            model_name='wosinvo',
            name='tile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tile.tile'),
        ),
    ]
