# Generated by Django 4.1.7 on 2023-09-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invocation', '0003_submissioninvo_tile_wosinvo_tile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wosinvo',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wosinvo',
            name='type',
            field=models.CharField(choices=[('XP', 'Skilling'), ('KC', 'Bossing'), ('LV', 'Levels')], default='LV', max_length=2),
        ),
    ]
