# Generated by Django 4.1.7 on 2023-09-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invocation', '0005_remove_submissioninvo_tile_remove_wosinvo_tile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOMInvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('XP', 'Skilling'), ('KC', 'Bossing'), ('LV', 'Levels')], default='LV', max_length=2)),
                ('amount', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='WOSInvo',
        ),
    ]
