# Generated by Django 4.1.7 on 2023-09-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0017_alter_tile_invocation_type'),
        ('invocation', '0006_wominvo_delete_wosinvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioninvo',
            name='tile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tile.tile'),
        ),
        migrations.AddField(
            model_name='wominvo',
            name='tile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tile.tile'),
        ),
    ]
