# Generated by Django 4.1.7 on 2023-09-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invocation', '0008_wominvo_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wominvo',
            name='names',
            field=models.CharField(default='', help_text='Name of skills or bosses to track. Leave empty for all. Separate by comma', max_length=256),
        ),
    ]
