# Generated by Django 4.1.7 on 2023-09-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invocation', '0010_wominvo_current_amount_alter_wominvo_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wominvo',
            name='current_amount',
        ),
    ]
