# Generated by Django 4.1.7 on 2023-09-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invocation', '0011_remove_wominvo_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wominvo',
            name='type',
            field=models.CharField(choices=[('XP', 'Experience'), ('KC', 'Bossing'), ('LV', 'Levels')], default='LV', max_length=2),
        ),
    ]
