# Generated by Django 4.1.7 on 2023-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='board_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='bingo',
            name='board_type',
            field=models.CharField(choices=[('square', 'SQUARE'), ('snake', 'SNAKE'), ('shootsandladders', 'SHOOTS AND LADDERS')], default='square', max_length=16),
        ),
    ]
