# Generated by Django 4.1.7 on 2023-07-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_bingo_board_size_bingo_board_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='max_score',
            field=models.IntegerField(default=-1),
        ),
    ]
