# Generated by Django 4.2.7 on 2023-11-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Make the bingo visible from main page'),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='is_team_public',
            field=models.BooleanField(default=False, help_text="Can players view other teams' boards?"),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='max_players_in_team',
            field=models.IntegerField(default=10, help_text='What is the maximum number of players in a team'),
        ),
    ]
