# Generated by Django 4.1.7 on 2023-08-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_alter_bingo_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='can_players_create_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bingo',
            name='max_players_in_team',
            field=models.IntegerField(default=0),
        ),
    ]
