# Generated by Django 4.2.7 on 2023-11-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_alter_bingo_is_public_alter_bingo_is_team_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='competition_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bingo',
            name='competition_verification_code',
            field=models.CharField(default='', max_length=64),
        ),
    ]
