# Generated by Django 4.2.7 on 2023-11-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_bingo_competition_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='end_date',
            field=models.DateTimeField(help_text='Ending date and time of bingo.'),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='max_players_in_team',
            field=models.IntegerField(default=10, help_text='Maximum number of players in a team'),
        ),
    ]
