# Generated by Django 4.1.7 on 2023-08-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_bingo_can_players_create_team_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
