# Generated by Django 4.2.7 on 2023-11-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_alter_bingo_end_date_alter_bingo_max_players_in_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='max_team_count',
            field=models.IntegerField(default=3, help_text='Maximum number of teams in the bingo'),
        ),
    ]
