# Generated by Django 4.1.7 on 2023-08-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_delete_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
