# Generated by Django 4.2.7 on 2023-11-08 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('bingo', '0006_bingo_max_team_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player'),
        ),
        migrations.AddField(
            model_name='bingo',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='board_size',
            field=models.IntegerField(default=4, help_text='Width/Height size of the board. THIS CANNOT BE CHANGED LATER'),
        ),
    ]
