# Generated by Django 4.1.7 on 2023-08-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0006_bingo_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
