# Generated by Django 4.2.7 on 2023-11-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0007_bingo_creator_bingo_is_paid_alter_bingo_board_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
