# Generated by Django 4.2.7 on 2023-11-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0008_bingo_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='board_size',
            field=models.IntegerField(default=4, help_text='Width/Height size of the board'),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='is_game_over_on_finish',
            field=models.BooleanField(default=False, help_text='Does the game finish when a team reaches maximum points?'),
        ),
    ]
