# Generated by Django 4.1.7 on 2023-08-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0009_alter_bingo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='is_game_over_on_finish',
            field=models.BooleanField(default=False),
        ),
    ]
