# Generated by Django 4.1.7 on 2023-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0010_bingo_is_game_over_on_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
