# Generated by Django 4.1.7 on 2023-09-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0011_bingo_is_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
