# Generated by Django 4.1.7 on 2023-09-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0014_bingo_is_row_col_extra_alter_bingo_board_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='img',
            field=models.ImageField(blank=True, help_text='Image displayed in home page', null=True, upload_to=''),
        ),
    ]
