# Generated by Django 4.1.7 on 2023-09-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0015_alter_bingo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='board_size',
            field=models.IntegerField(default=5, help_text='Width/Height size of the board. THIS CANNOT BE CHANGED LATER'),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='board_type',
            field=models.CharField(choices=[('square', 'SQUARE'), ('snake', 'SNAKE'), ('shootsandladders', 'SHOOTS AND LADDERS')], default='square', help_text='Board type (Not implemented)', max_length=16),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='can_players_create_team',
            field=models.BooleanField(default=True, help_text='Can the players create the own teams?'),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='is_game_over_on_finish',
            field=models.BooleanField(default=False, help_text='Does the game finish when a team reaches maximum points? (Not implemented)'),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='is_public',
            field=models.BooleanField(default=False, help_text="Can someone who hasn't joined the bingo see it? (Not implemented)"),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='is_row_col_extra',
            field=models.BooleanField(default=True, help_text='Do teams get extra points for completing a row or column?'),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='is_team_public',
            field=models.BooleanField(default=False, help_text="Can a player view other teams' boards? (Not fully tested)"),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='max_players_in_team',
            field=models.IntegerField(default=0, help_text='If players can create their teams what is the maximum team size? (0 Means no limit)'),
        ),
    ]
