# Generated by Django 4.1.7 on 2023-09-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0016_alter_bingo_board_size_alter_bingo_board_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='end_date',
            field=models.DateTimeField(help_text='Starting date and time of bingo. UTC not local timezone'),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='start_date',
            field=models.DateTimeField(help_text='Starting date and time of bingo. UTC not local timezone'),
        ),
    ]
