# Generated by Django 4.1.7 on 2023-09-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0019_bingo_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
    ]
