# Generated by Django 4.1.7 on 2023-09-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0020_alter_bingo_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='max_score',
            field=models.IntegerField(default=-1),
        ),
    ]
