# Generated by Django 4.1.7 on 2023-10-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0021_alter_bingo_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='img',
            field=models.ImageField(blank=True, help_text='Image displayed in home page. Recommended size: 270x200px', null=True, upload_to=''),
        ),
    ]
