# Generated by Django 4.1.7 on 2023-11-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0023_alter_bingo_description_alter_bingo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='end_date',
            field=models.DateTimeField(help_text='Starting date and time of bingo.'),
        ),
        migrations.AlterField(
            model_name='bingo',
            name='start_date',
            field=models.DateTimeField(help_text='Starting date and time of bingo.'),
        ),
    ]
