# Generated by Django 4.1.7 on 2023-08-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='bingo_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='ranking',
            field=models.IntegerField(default=-1),
        ),
    ]
