# Generated by Django 4.1.7 on 2023-08-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_bingo_score_alter_team_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='bingo_score',
            new_name='score',
        ),
    ]
