# Generated by Django 4.1.7 on 2023-10-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='discord_webhook',
            field=models.CharField(blank=True, help_text="Webhook URL for your channel. Leave empty if you don't want to use.", max_length=256, null=True),
        ),
    ]
